### ISSUE TITLE
ssh key invalid format message

### ISSUE THREAD

**Issue by kkaiser** [udondan/cdk-ec2-key-pair#23]
Hello,

thanks for this fantastic package.

When I download the private key from secrets manager and the connect to the instance I will get an error:
```bash
ssh -i root_key.pem ubuntu@myip
load pubkey "root_key.pem": invalid format
```

It still connects fine after this but what seems to resolve the issue is this command:
```bash
ssh-keygen -f root_key.pem -p -y
```
So even though I don't set a password the warning seems to be gone after connecting. Is that something you can do something about or is it an AWS SDK issue?

I got the hint here: https://serverfault.com/a/1025451

Omitting the `-p` option did not work like suggested here: I https://sjsadowski.com/invalid-format-ssh-key/

**Comment by udondan** [comment]
Hi @kkaiser,

the KeyPair is generated by AWS via API. So if there is anything wrong it probably cannot and should not be fixed in this package. When you manually generate a PEM key in the AWS EC2 console, you should see the same exact thing.

> `ssh-keygen -f root_key.pem -p -y`

From my understanding, this command will convert the PEM/RSA key to an RFC 4716/SSH2 key. Don't know why this would make a difference. Both keys are valid. But the "error" message also said that it attempted to load the key as a **public** key. Of course, then this will fail since it's a private key.

ssh is a bit stupid at times. Maybe it just understands the OpenSSH format better in that case and does not attempt to load it as a pub key. I don't know. But I also cannot reproduce that message here. The original keys don't cause any such message.

Cheers,
Daniel

**Comment by kkaiser** [comment]
Thanks for your reply and clarifying this is an AWS issue.

Also all you said is fair :) I thought it was worth asking also it might be useful to others as well to post this question here if they are looking for it. I can see that the key gets converted. Before it will start with:
`-----BEGIN RSA PRIVATE KEY-----`
and after with:
`-----BEGIN OPENSSH PRIVATE KEY-----`

I do use the private key to connect. Like it says in the blogposts I think the error message is just misleading. Also this is not an error but just a warning the connection is fine.

Just for completeness sake my ssh client runs on Windows with MinGW OpenSSH_8.3p1 and ssh server is OpenSSH_8.2p1 on Ubuntu 20.04.1 LTS.

Maybe I will ask the AWS support about this but here I will close the issue. Cheers!
