### ISSUE TITLE
Update from 1.x fails

### ISSUE THREAD

**Issue by ilko-rbi** [udondan/cdk-ec2-key-pair#31]
Hi,

what is the correct way to update existing stacks to the 2.2.0 from 1.x version - as stated in the documentation the update fails with the message "Received response status [FAILED] from custom resource. Message returned: Once created, a key cannot be modified or accessed. Therefore the public key can only be stored, when the key is created. | Full error in CloudWatch ..." and yes, the rollback finishes successfully. However, I didn't get it how to upgrade - we have to run this fully automated, because we have huge number of resources - is this possible without dropping the stack?

thanks again!

**Comment by udondan** [comment]
I don't think there is a way to upgrade from v1 to v2 without destroying. Too much had changed under the hood. Honestly, too long ago, so I don't remember the details, but I was pretty explicit in the description of version [2.0.0](https://github.com/udondan/cdk-ec2-key-pair/releases/tag/v2.0.0) 😸 

> Incompatible to v1.x - This will not only require you to update your code, but also will destroy your keys and secrets and re-generate them!

To be on the safe side, you should first delete the old construct using the old package version, then install the new package and then add a new key.

If you do it in one go, I'm quite sure it will fail, because the new code won't be able to destroy the old resources.

**Comment by ilko-rbi** [comment]
Ok, we have then to implement some extra workflow before pushing the changes related to this. Thanks for the prompt reply!
