### ISSUE TITLE
Add support type of Key: RSA or ed25519

### ISSUE THREAD

**Issue by vechorko** [udondan/cdk-ec2-key-pair#38]
In a current moment Key pairs  support 2 types: RSA and ed25519. 

If it possible I want to ask to add opportunity to choose key type

**Comment by udondan** [comment]
Hi Dmitry,

I looked into this for quite some time but wasn't able to figure it out. I created #39, which so far is a partial implementation.

The problem is, the [forge](https://github.com/digitalbazaar/forge) library seems to have limited support for ed25519 keys. I haven't found a way to generate the public key from the key pair.

Maybe in a future version of forge.

Cheers,
Daniel

**Comment by AllanOricil** [comment]
@udondan we need this feature for Amazon Linux 2023 https://docs.aws.amazon.com/linux/al2023/ug/ssh-host-keys-disabled.html

**Comment by udondan** [comment]
@vechorko @AllanOricil Support for ED25519 is now available in version 4.0.0
