### ISSUE TITLE
Type 'ConstructNode' is missing the following properties from type 'Node'

### ISSUE THREAD

**Issue by thisentirecitymustbepurged** [udondan/cdk-ec2-key-pair#45]
Hi, 

I am a AWS noob trying to learn EC2.

TS Error: `Type 'ConstructNode' is missing the following properties from type 'Node'`
JS Error when trying to `cdk bootstrap`: `scope.node.addChild is not a function`

I ended up in this situation by following this: https://aws.amazon.com/getting-started/guides/deploy-webapp-ec2

![image](https://user-images.githubusercontent.com/20511483/151943552-b24fefbd-cf69-4593-93f7-2b72a8d29630.png)
 
While the same code with this `package.json` works fine:
![image](https://user-images.githubusercontent.com/20511483/151977601-a0f007ae-446f-41bf-a8ab-a29be19ae4ad.png)

This seems like a mismatch in the versions of the `constructs` module. Any advice on how to approach these type of problems? I hope this is not gonna be the theme when trying to stitch shit together with EC2 on your own. 

My intuition tells me the most cost efficient way about this is just to find a version combination that works. 

Sorry if this is not the right place, but I have no idea where else to talk about this issue (any suggestions if so?)

**Comment by udondan** [comment]
Hi,

yeah, you're having some mixed versions there. In your `package.json` you have both the `aws-cdk-lib` (= CDK v2) and those starting with `@aws-cdk/` (= CDK v1). Also you're using version 3.x of this lib. 3.x is for CDK v2. Vor CDK 1 you would need to use 2.x of this lib.

In your code on the left side you import the `@aws-cdk/`, so you're having a v1 application. But since the 3.x version of `cdk-ec2-key-pair` is for CDK v2, you're getting this error.

I'd suggest you remove everything related to CDK 1 only use v2. Your imports in the ts file then should look something like this:

```typescript
import cdk = require('aws-cdk-lib');
import ec2 = require('aws-cdk-lib/aws-ec2');
import iam = require('aws-cdk-lib/aws-iam');
import s3assets = require('aws-cdk-lib/aws-s3-assets');
import { Construct } from 'constructs';
import { KeyPair } from 'cdk-ec2-key-pair';
```

And on line 9 you need to replace `cdk.Construct` with just `Construct`.

In case you haven't found it yet, here is a slack channel for all things CDK: https://cdk.dev/

Hope this helps,
Daniel

**Comment by thisentirecitymustbepurged** [comment]
Ah damn, if I wasn't dumb I could've saved you the time of having to explain this shit again. I saw a similar explanation from you on another issue. For whatever reason I had a brainfart and thought the `@aws-something` modules are the "latest", even though they literally start with version `1`. 

Thanks. Take the $5 and buy yourself something you like.

**Comment by udondan** [comment]
Ah no problem at all. Happy I could help! Thanks for the ☕! Not needed at all. To see that my package now is mentioned in official AWS guides already sweetened my day 😸
