### ISSUE TITLE
CDK v2 compatible versions in nuget?

### ISSUE THREAD

**Issue by xsampedro** [udondan/cdk-ec2-key-pair#46]
The last version available is 2.2.1: https://www.nuget.org/packages/CDK.EC2.KeyPair

**Comment by jkuek** [comment]
Yes please, what are the chances of getting this?

**Comment by McDoit** [comment]
Yeah its greatly missed @udondan :)

**Comment by udondan** [comment]
Well the reason why there ain't no v2 compatible version is that I'm pretty convinced the v1 version actually never worked. 😸 It was building and I never had any complains - though I guess that was because just nobody was actually using it. I never was able to make cdk-iam-floyd work with .Net - but now that it's no longer a dependency (#49) it _might_ work.

**Comment by McDoit** [comment]
At least one of the downloads of 1.7.4 on Nuget are from me

Can't say how happy i am to see some constructs for dotnet CDK usage, and i hope its possible to add it to Nuget again!

**Comment by udondan** [comment]
I just published 3.3.1: https://www.nuget.org/packages/CDK.EC2.KeyPair/3.3.1 - Completely untested. 😸
